"""Stable identities for persisted conversations."""

from __future__ import annotations

import os
from pathlib import Path
from uuid import UUID, uuid4, uuid5

# A fixed application namespace makes legacy backfills repeatable while keeping
# them distinct from UUIDs generated by other uuid5 users.
_LEGACY_CONVERSATION_NAMESPACE = UUID("c891e293-f14f-4f18-9945-a6ca271337d7")


def new_conversation_id() -> str:
    """Return a new opaque identity for a newly persisted conversation."""
    return str(uuid4())


def legacy_conversation_id(path: str | Path) -> str:
    """Return the deterministic identity of a marked legacy session file.

    The normalized absolute path includes the owning session directory, so
    equal filenames in independently selected directories never collide.
    """
    resolved = str(Path(path).expanduser().resolve(strict=False))
    return str(uuid5(_LEGACY_CONVERSATION_NAMESPACE, os.path.normcase(resolved)))
