"""Unit tests for :mod:`api.auth.config_write`.

The audit caught two latent shapes:

1. ``_dump_toml_like`` silently drops non-section root keys — the
   audit's wording was "config.toml ... pre-section scalar in
   config.toml disappears the next time write_auth_section runs."
   We document the limitation by asserting the actual behaviour and
   warn loudly via a log so an operator who lands a top-level scalar
   in their config sees it.
2. No general TOML serialiser is implied — strings / ints / bools /
   lists only.  Tests pin the supported shapes.
"""

import pytest

from kohakuterrarium.api.auth.config_write import (
    config_toml_path,
    read_config_toml,
    write_auth_section,
)


@pytest.fixture
def cfg(tmp_path, monkeypatch):
    monkeypatch.setenv("KT_CONFIG_DIR", str(tmp_path))
    yield tmp_path


class TestWriteAuthSection:
    def test_fresh_file_creates_auth_section(self, cfg):
        write_auth_section({"host_token": "abc"})
        data = read_config_toml()
        assert data["auth"]["host_token"] == "abc"

    def test_merge_preserves_existing_fields(self, cfg):
        # Pre-seed admin_token + an unrelated section.
        (cfg / "config.toml").write_text(
            '[auth]\nadmin_token = "preexist"\n\n' '[ui]\ntheme = "dark"\n',
            encoding="utf-8",
        )
        write_auth_section({"host_token": "new"})
        data = read_config_toml()
        assert data["auth"]["admin_token"] == "preexist"
        assert data["auth"]["host_token"] == "new"
        # Unrelated sections survive (their structure may be re-sorted
        # but the key/value persists).
        assert data["ui"]["theme"] == "dark"

    def test_overwrite_existing_key(self, cfg):
        write_auth_section({"host_token": "old"})
        write_auth_section({"host_token": "new"})
        data = read_config_toml()
        # host_token lives under [auth], never at top level.
        assert "host_token" not in data
        assert data["auth"]["host_token"] == "new"

    def test_supported_value_shapes(self, cfg):
        write_auth_section(
            {
                "host_token": "abc",
                "loopback_bypass": False,
                "session_expire_hours": 24,
                "registration": "invite_only",
            }
        )
        # Round-trip through ``read_config_toml`` (= tomllib parse).
        data = read_config_toml()
        section = data["auth"]
        assert section["host_token"] == "abc"
        assert section["loopback_bypass"] is False
        assert section["session_expire_hours"] == 24
        assert section["registration"] == "invite_only"

    def test_string_escaping_preserves_quotes_and_backslashes(self, cfg):
        # Defensive: a token containing a double-quote or a backslash
        # must survive serialisation + parse.  Tokens generated by
        # ``secrets.token_hex`` never contain these, but operators
        # who set ``host_token`` manually might.
        weird = 'has"quote\\backslash'
        write_auth_section({"host_token": weird})
        data = read_config_toml()
        assert data["auth"]["host_token"] == weird

    def test_creates_parent_dir(self, tmp_path, monkeypatch):
        # Nested config dir that doesn't exist yet.
        target = tmp_path / "nested" / "deeper"
        monkeypatch.setenv("KT_CONFIG_DIR", str(target))
        write_auth_section({"host_token": "x"})
        assert (target / "config.toml").is_file()


class TestDumperLimitations:
    """Pin the documented behavioural limitations.

    These tests exist so the next reader knows the dumper is
    intentionally minimal and changing it has tests to update.
    """

    def test_top_level_scalars_raise(self, cfg):
        # An operator who pre-seeded a top-level scalar in their
        # config.toml would previously have lost it silently on the
        # next ``write_auth_section`` call (the pre-fix behaviour
        # logged a warning the operator likely never saw).  The fix
        # raises ValueError so the rewrite ABORTS and the original
        # file is left intact — failing loudly beats corrupting user
        # data.
        (cfg / "config.toml").write_text(
            'version = 7\n\n[auth]\nhost_token = "x"\n',
            encoding="utf-8",
        )
        with pytest.raises(ValueError, match="top-level scalars"):
            write_auth_section({"admin_token": "y"})
        # Original file untouched.
        data = read_config_toml()
        assert data["version"] == 7
        assert data["auth"]["host_token"] == "x"
        assert "admin_token" not in data["auth"]

    def test_nested_table_raises_instead_of_silent_corruption(self, cfg):
        # Pre-existing nested table in config.toml: tomllib parses it
        # as a nested dict.  Our minimal dumper used to stringify
        # the nested dict via repr() — silent corruption.  Now it
        # raises so a future caller who passes nested data sees the
        # limitation explicitly instead of getting a broken config
        # file written under their feet.
        (cfg / "config.toml").write_text(
            '[auth]\nhost_token = "x"\n\n' '[other.deeper]\nkey = "value"\n',
            encoding="utf-8",
        )
        with pytest.raises(ValueError, match="nested tables"):
            write_auth_section({"admin_token": "y"})


class TestPathResolution:
    def test_honours_kt_config_dir(self, cfg):
        assert config_toml_path() == cfg / "config.toml"


class TestReadConfigToml:
    def test_missing_file_returns_empty(self, cfg):
        assert read_config_toml() == {}

    def test_malformed_toml_returns_empty_with_warning(self, cfg):
        # Garbage at top level — tomllib raises; the helper catches
        # and logs.  Caller should not have to wrap the read.
        (cfg / "config.toml").write_text(
            "this is not = [ valid toml\nat all", encoding="utf-8"
        )
        assert read_config_toml() == {}

    def test_unreadable_file_returns_empty(self, cfg, monkeypatch):
        # Force an OSError on read by pointing at a non-file.
        path = cfg / "config.toml"
        path.mkdir()  # directory where the loader expects a file
        try:
            assert read_config_toml() == {}
        finally:
            path.rmdir()


class TestToplevelValueShapes:
    """Defensive: `_toml_value` covers the path for non-{bool,int,str,list}
    values via a stringification fallback."""

    def test_list_of_strings(self, cfg):
        write_auth_section({"hosts": ["a", "b", "c"]})
        data = read_config_toml()
        assert data["auth"]["hosts"] == ["a", "b", "c"]

    def test_falsy_fallback_emits_repr(self, cfg):
        # Pass an unsupported type (None) — _toml_value's catch-all
        # branch turns it into a quoted string.  Defensive but
        # documented; pin so a future "raise on unsupported" change
        # has a clear failing test to discuss.
        write_auth_section({"weird": None})
        data = read_config_toml()
        # The exact emitted form is implementation-defined; just
        # assert the key survives round-trip as a string-shaped value.
        assert "weird" in data["auth"]
